name: Build, Package, and Release Bot

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Latest version of checkout

    - name: Set up Python
      uses: actions/setup-python@v4  # Latest version of setup-python
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Extract Version
      id: extract_version
      run: |
        version=$(python -c 'exec(open("__version__.py").read()); print(__version__)')
        echo "VERSION=$version" >> $GITHUB_ENV

    - name: Build installer
      run: |
        pip install pyinstaller
        pyinstaller --onefile gui.py

        # Move the installer to a temp directory based on OS
        if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            mv dist/gui /tmp/gui-installer
        elif [ "${{ matrix.os }}" == "macos-latest" ]; then
            mv dist/gui /tmp/gui-installer
        fi
      shell: bash  # Use Bash shell for this step

    - name: Build installer for Windows
      if: matrix.os == 'windows-latest'
      run: |
        mv dist/gui.exe C:\temp\gui-installer.exe
      shell: pwsh  # Use PowerShell for Windows

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: bot-installer-${{ matrix.os }}
        path: |
          ${{ matrix.os == 'ubuntu-latest' && '/tmp/gui-installer' || '' }}
          ${{ matrix.os == 'windows-latest' && 'C:\\temp\\gui-installer.exe' || '' }}
          ${{ matrix.os == 'macos-latest' && '/tmp/gui-installer' || '' }}

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create Git Tag
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git tag v${{ env.VERSION }}
        git push origin v${{ env.VERSION }}

    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ env.VERSION }}
        release_name: Release v${{ env.VERSION }}
        body: |
          ## Release v${{ env.VERSION }}
          - Automatic release from GitHub Actions
        draft: false
        prerelease: false

    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: path/to/your/built/installer
        asset_name: installer-${{ matrix.os }}.zip
        asset_content_type: application/zip
