name: Build, Package, and Release Bot

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger of the workflow

permissions:
  contents: write  # Ensure the GITHUB_TOKEN has write permissions for releases

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Extract Version
      id: get_version
      run: |
        # Extract version from __version__.py
        echo "VERSION=$(python -c 'from __version__ import __version__; print(__version__)')" >> $GITHUB_ENV
        echo "Version is $VERSION"

    - name: Build installer
      run: |
        pip install pyinstaller
        pyinstaller --onefile gui.py

        # Move the installer to a temp directory
        if [ "${{ matrix.os }}" == "ubuntu-latest" ] || [ "${{ matrix.os }}" == "macos-latest" ]; then
            mv dist/gui /tmp/gui-installer  # For Linux and macOS
        fi
      shell: bash

    - name: Build installer for Windows
      if: matrix.os == 'windows-latest'
      run: |
        Move-Item -Path dist\gui.exe -Destination C:\temp\gui-installer.exe
      shell: pwsh

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: bot-installer-${{ matrix.os }}
        path: |
          ${{ matrix.os == 'ubuntu-latest' && '/tmp/gui-installer' || '' }}
          ${{ matrix.os == 'windows-latest' && 'C:\\temp\\gui-installer.exe' || '' }}
          ${{ matrix.os == 'macos-latest' && '/tmp/gui-installer' || '' }}

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Download artifacts from each OS
    - name: Download Ubuntu artifact
      uses: actions/download-artifact@v3
      with:
        name: bot-installer-ubuntu-latest
      if: success() && always()

    - name: Download Windows artifact
      uses: actions/download-artifact@v3
      with:
        name: bot-installer-windows-latest
      if: success() && always()

    - name: Download macOS artifact
      uses: actions/download-artifact@v3
      with:
        name: bot-installer-macos-latest
      if: success() && always()

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ env.VERSION }}  # Use the unique version number as the tag
        release_name: "Release v${{ env.VERSION }}"
        body: |
          **Release version:** v${{ env.VERSION }}
        draft: false
        prerelease: false

    # Upload release assets for Ubuntu/macOS
    - name: Upload Ubuntu/MacOS release assets
      uses: actions/upload-release-asset@v1
      if: success() && always() && startsWith(matrix.os, 'ubuntu') || startsWith(matrix.os, 'macos')
