name: Build, Package, and Release Bot

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger of the workflow

permissions:
  contents: write  # Ensure the GITHUB_TOKEN has write permissions for releases

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Extract Version (Linux/macOS)
        id: extract_version_unix
        if: runner.os != 'Windows'
        run: |
          VERSION=$(python -c "from __version__ import __version__; print(__version__)")
          echo "VERSION=${VERSION}"
          echo "::set-output name=version::${VERSION}"
        shell: bash

      # Build macOS app and create DMG
      - name: Build and package for macOS
        if: matrix.os == 'macos-latest'
        run: |
          # Install PyInstaller and build the .app
          pip install pyinstaller
          pyinstaller --onefile --windowed --name=tbuddy --target-arch x86_64 gui.py

          mkdir -p dist/dmg
          rm -rf dist/dmg/*
          cp -r "dist/tbuddy.app" dist/dmg
          
          # Verify the contents of the dist folder
          echo "Listing contents of dist folder"
          ls -R dist/
          
          # Install create-dmg tool
          npm install --global create-dmg

          # Create the DMG, with a specific title to avoid versioning issues
          create-dmg \
            --volname "tbuddy" \
            --volicon "tbuddy.ico" \
            --window-pos 200 120 \
            --window-size 600 300 \
            --icon-size 100 \
            --icon "tbuddy.app" 175 120 \
            --hide-extension "tbuddy.app" \
            --app-drop-link 425 120 \
            "dist/tbuddy.dmg" \
            "dist/dmg/"

          # Verify the DMG was created
          echo "Listing contents of dist after DMG creation"
          ls -R dist/
        shell: bash

      - name: Upload macOS DMG
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v3
        with:
          name: tbuddyInstaller-macos.dmg
          path: ./dist/tbuddyInstaller.dmg

      # Build installers for Windows and Ubuntu
      - name: Build installer (Windows and Ubuntu)
        if: matrix.os != 'macos-latest'
        run: |
          pip install pyinstaller
          pyinstaller --onefile gui.py
        shell: bash

      - name: Upload Windows Installer
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v3
        with:
          name: tbuddy-installer-windows
          path: ./dist/gui.exe

      - name: Upload Ubuntu Installer
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v3
        with:
          name: tbuddy-installer-ubuntu
          path: ./dist/gui

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Release Version
        run: echo "VERSION=${{ needs.build.outputs.version }}" >> $GITHUB_ENV

      - name: Download Ubuntu artifact
        uses: actions/download-artifact@v3
        with:
          name: tbuddy-installer-ubuntu
          path: ./downloads

      - name: Download Windows artifact
        uses: actions/download-artifact@v3
        with:
          name: tbuddy-installer-windows
          path: ./downloads

      - name: Download macOS DMG artifact
        uses: actions/download-artifact@v3
        with:
          name: tbuddyInstaller-macos.dmg
          path: ./downloads

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ needs.build.outputs.version }}
          release_name: "tbuddy Release v${{ needs.build.outputs.version }}"
          body: |
            **Release version:** v${{ needs.build.outputs.version }}
          draft: false
          prerelease: false

      - name: Upload Ubuntu release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./downloads/tbuddy-installer-ubuntu
          asset_name: tbuddy-installer-ubuntu-v${{ needs.build.outputs.version }}
          asset_content_type: application/octet-stream

      - name: Upload macOS release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./downloads/tbuddyInstaller-macos.dmg
          asset_name: tbuddyInstaller-macos-v${{ needs.build.outputs.version }}.dmg
          asset_content_type: application/octet-stream

      - name: Upload Windows release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./downloads/tbuddy-installer-windows.exe
          asset_name: tbuddy-installer-windows-v${{ needs.build.outputs.version }}.exe
          asset_content_type: application/octet-stream
