name: Cleanup Old Artifacts

# Add workflow_dispatch to enable manual triggers
on:
  workflow_dispatch:  # Allows manual triggering from GitHub Actions UI
  schedule:           # (Optional) Keep the cron job if you also want to trigger it automatically
    - cron: "0 0 * * 0"  # Runs every Sunday at midnight

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Delete unused artifacts
        run: |
          # Assuming you want to keep artifacts from the last 30 days
          find./github/workspace -type f -name "*.zip" -mtime +30 -exec rm {} \;
          # Adjust the find command to fit your artifact naming and directory structure

      - name: Verify cleanup
        run: |
          echo "Cleanup completed. Remaining artifacts:"
          ls -R./github/workspace