name: Cleanup Old Artifacts

on:
  schedule:
    - cron: "0 0 * * 0"  # Runs every week

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: List all artifacts
        run: |
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               https://api.github.com/repos/${{ github.repository }}/actions/artifacts \
               | jq '.artifacts[] | {name, id, expired: (.expired==false)}'

      - name: Delete old artifacts (older than 30 days)
        run: |
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               https://api.github.com/repos/${{ github.repository }}/actions/artifacts \
               | jq -r '.artifacts[] | select(.expired==false) | .id' \
               | xargs -I {} curl -X DELETE \
               -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               https://api.github.com/repos/${{ github.repository }}/actions/artifacts/{}
